"""Updated Schemas

Revision ID: 9ac23f0ca362
Revises: a8d53eb498a5
Create Date: 2024-05-02 22:50:04.802533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ac23f0ca362'
down_revision: Union[str, None] = 'a8d53eb498a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registered_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'registered_at')
    # ### end Alembic commands ###
