"""updated models using copilot 2

Revision ID: a6c778125f94
Revises: ec5de9fb5383
Create Date: 2024-06-05 22:58:59.586659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6c778125f94'
down_revision: Union[str, None] = 'ec5de9fb5383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_request_id_fkey', 'events', type_='foreignkey')
    op.drop_column('events', 'request_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('events_request_id_fkey', 'events', 'requests', ['request_id'], ['request_id'])
    # ### end Alembic commands ###
